version: '3.8'

services:
  glantai_app:
    build: 
      context: .
    container_name: glantai_container
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=sqlite:///./database.db 
    volumes:
      - .:/app

